version: '3.9'
services:
  postgres:
    image: 'postgres:16.2-alpine3.19'
    env_file:
      - '.env'
    restart: 'on-failure'
    ports:
      - "5432:5432"
    volumes:
      - .db_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  bot:
    image: 'book_bot'
    restart: 'on-failure'
    env_file:
      - '.env'
    volumes:
      - .bot_data:/var/lib/bot/data/
    depends_on:
      postgres:
        condition: service_healthy
  migrations:
    image: 'book_bot'
    restart: 'no'
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "heads"]

volumes:
  db_data:
  bot_data: